/*
* @description : 파이어베이스 연결하면 자동으로 만들어지는 파일
* 가만히 냅두면 됨 !!!
* */






// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CCPYXS-8eihEexzScyM8tU284u3O0TI',
    appId: '1:139634558424:android:faea696cf80b06e9c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDim3URWw-28aahG_4vPAx-y9EXzs4Dpi0',
    appId: '1:139634558424:ios:a5466aecd9256896c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    iosClientId: '139634558424-fl2jdqe7je55lrvemlm3idr1vie1mffl.apps.googleusercontent.com',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDim3URWw-28aahG_4vPAx-y9EXzs4Dpi0',
    appId: '1:139634558424:ios:a5466aecd9256896c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    iosClientId: '139634558424-fl2jdqe7je55lrvemlm3idr1vie1mffl.apps.googleusercontent.com',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBRdftAXjmo0js4Hobykvfmu0R9bo92s',
    appId: '1:139634558424:web:5ae59f1ce3dc6f56c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    authDomain: 'thedaymerge-54b72.firebaseapp.com',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    measurementId: 'G-L65WSBYYN9',
  );

}