name: thedaymerge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4

  # 캘린더/날짜 관련
  table_calendar: ^3.0.0
  dotted_border: ^2.0.0
  intl: ^0.18.0

  # 이미지 & OCR & 통신
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  http: ^1.1.0

  # 기타
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

  provider: ^6.1.5+1

  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFF0F3"
    theme_color: "#FF6B81"

flutter:
  uses-material-design: true

  assets:
    - .env
