// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_kXhZm2JVfRKdQHlAuUxfY7No7uILGfI',
    appId: '1:920858695792:android:0ed719ea762bcdf8a07cb5',
    messagingSenderId: '920858695792',
    projectId: 'tdm2-13be0',
    storageBucket: 'tdm2-13be0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7nDVtuCqLHNScpFAhd8ZFtZDCuTxVY4k',
    appId: '1:920858695792:ios:f98ce12da8799996a07cb5',
    messagingSenderId: '920858695792',
    projectId: 'tdm2-13be0',
    storageBucket: 'tdm2-13be0.firebasestorage.app',
    iosClientId: '920858695792-kvl14jmv6v710v3e5tst7bfjftsb8dtc.apps.googleusercontent.com',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7nDVtuCqLHNScpFAhd8ZFtZDCuTxVY4k',
    appId: '1:920858695792:ios:f98ce12da8799996a07cb5',
    messagingSenderId: '920858695792',
    projectId: 'tdm2-13be0',
    storageBucket: 'tdm2-13be0.firebasestorage.app',
    iosClientId: '920858695792-kvl14jmv6v710v3e5tst7bfjftsb8dtc.apps.googleusercontent.com',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4iXnbk6KvxcOO-pIkftz8fGUemGTz2U',
    appId: '1:920858695792:web:3dfa0ea3552b8a31a07cb5',
    messagingSenderId: '920858695792',
    projectId: 'tdm2-13be0',
    authDomain: 'tdm2-13be0.firebaseapp.com',
    storageBucket: 'tdm2-13be0.firebasestorage.app',
    measurementId: 'G-JP4ET949FP',
  );

}