// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBRdftAXjmo0js4Hobykvfmu0R9bo92s',
    appId: '1:139634558424:web:826f2bb0881fc62ec49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    authDomain: 'thedaymerge-54b72.firebaseapp.com',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    measurementId: 'G-JEMJHNGRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CCPYXS-8eihEexzScyM8tU284u3O0TI',
    appId: '1:139634558424:android:7f1ad3eaffc0c185c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDim3URWw-28aahG_4vPAx-y9EXzs4Dpi0',
    appId: '1:139634558424:ios:a5466aecd9256896c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDim3URWw-28aahG_4vPAx-y9EXzs4Dpi0',
    appId: '1:139634558424:ios:a5466aecd9256896c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    iosBundleId: 'com.thedaymerge.thedaymerge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJBRdftAXjmo0js4Hobykvfmu0R9bo92s',
    appId: '1:139634558424:web:5ae59f1ce3dc6f56c49ead',
    messagingSenderId: '139634558424',
    projectId: 'thedaymerge-54b72',
    authDomain: 'thedaymerge-54b72.firebaseapp.com',
    storageBucket: 'thedaymerge-54b72.firebasestorage.app',
    measurementId: 'G-L65WSBYYN9',
  );
}
